=== BogdanEmilian/Assignment4_JavaTemplates/src/main/resources/queue.dtd
<!ELEMENT queue (task*)>
<!ELEMENT task (title,description, dueDate, status)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT dueDate (#PCDATA)>
<!ELEMENT status (#PCDATA)>

=== BogdanEmilian/Assignment4_JavaTemplates/src/main/resources/Task.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="template.xsl"?>
<!DOCTYPE queue SYSTEM "queue.dtd">
<queue xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="./queue.xsd">
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Bachelor's thesis</title>
		<description>Finish the application for the bachelor's thesis</description>
		<dueDate>20-06-2023</dueDate>
		<status>TODO</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Learn how to play guitar</title>
		<description>Learn the basic chords in order to play the guitar</description>
		<dueDate>24-12-2022</dueDate>
		<status>In progress</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Web Technologies project backend</title>
		<description>Finish the backend of the project</description>
		<dueDate>20-12-2022</dueDate>
		<status>TODO</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Web Technologies project frontend</title>
		<description>Finish the frontend of the project</description>
		<dueDate>10-01-2023</dueDate>
		<status>TODO</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Title 1</title>
		<description>Description 1</description>
		<dueDate>20-12-2022</dueDate>
		<status>DONE</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Title 2</title>
		<description>Description 2</description>
		<dueDate>20-12-2022</dueDate>
		<status>DONE</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Title 3</title>
		<description>Description 3</description>
		<dueDate>20-12-2022</dueDate>
		<status>DONE</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Title 4</title>
		<description>Description 4</description>
		<dueDate>20-12-2022</dueDate>
		<status>DONE</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Title 4</title>
		<description>Description 4</description>
		<dueDate>20-12-2022</dueDate>
		<status>DONE</status>
	</task>
	<task id="asd" href="https://www.google.com" comment="first task">
		<title>Title 5</title>
		<description>Description 5</description>
		<dueDate>20-12-2022</dueDate>
		<status>DONE</status>
	</task>
</queue>
